kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/devfile-samples/devfile-sample-code-with-quarkus.git'
    deployment.kubernetes.io/revision: '4'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"code-with-quarkus-demo:latest","namespace":"desantischris-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"code-with-quarkus-demo\")].image","paused":false}]
    isFromDevfile: 'true'
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '6954602140'
  name: code-with-quarkus-demo
  uid: 8f46a6eb-f212-44dc-af34-c4a408336333
  creationTimestamp: '2025-12-26T20:19:18Z'
  generation: 9
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2025-12-26T20:25:02Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/route-disabled': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
            'f:isFromDevfile': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"code-with-quarkus-demo"}':
                  'f:startupProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8081,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-12-26T21:42:36Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"code-with-quarkus-demo"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2025-12-27T09:42:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
      subresource: status
    - manager: member-operator
      operation: Update
      apiVersion: apps/v1
      time: '2025-12-27T09:42:38Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:replicas': {}
  namespace: desantischris-dev
  labels:
    app: code-with-quarkus-demo
    app.kubernetes.io/component: code-with-quarkus-demo
    app.kubernetes.io/instance: code-with-quarkus-demo
    app.kubernetes.io/name: code-with-quarkus-demo
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: quarkus
spec:
  replicas: 0
  selector:
    matchLabels:
      app: code-with-quarkus-demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: code-with-quarkus-demo
        deployment: code-with-quarkus-demo
    spec:
      containers:
        - resources:
            requests:
              cpu: 10m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: code-with-quarkus-demo
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /q/health/live
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/desantischris-dev/code-with-quarkus-demo@sha256:188da565618afa2c122cbe0347385a6c198243495f68d5e8327a70166e1ca710
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 9
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2025-12-26T21:35:33Z'
      lastTransitionTime: '2025-12-26T21:35:33Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2025-12-26T21:43:38Z'
      lastTransitionTime: '2025-12-26T20:19:18Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "code-with-quarkus-demo-7c4cff78f7" has successfully
        progressed.
